name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e

            # Load nvm & node
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && . "\$NVM_DIR/nvm.sh"
            nvm use 22

            cd ${{ secrets.APP_DIR }}

            echo "Resetting local changes..."
            git fetch origin
            git reset --hard origin/main

            echo "Backend setup..."
            cd server
            pnpm install --frozen-lockfile
            pm2 restart server || pm2 start index.js --name server

            echo "Building frontend..."
            cd ../client
            pnpm install
            pnpm build

            echo "Deploying frontend to nginx..."
            sudo mkdir -p /var/www/client
            sudo rm -rf /var/www/client/dist
            sudo cp -r dist /var/www/client/
            pm2 reset client 

            sudo chown -R www-data:www-data /var/www/client
            sudo chmod -R 755 /var/www/client

            sudo nginx -t
            sudo systemctl reload nginx
            
            pm2 restart client || pm2 start "serve -s dist -l 3000" --name client


            pm2 save
            echo "âœ… Deployment complete"
          EOF
